// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("414df310-74f5-4ee8-b9cf-f9b555d634ad")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("RandomImpls.Tests")]
